/**
 * Diacritic-aware `wordBoundariesRegex` for relationship typeahead.
 *
 * DO NOT wire via next.config `resolve.alias['payload/shared']` under Turbopack —
 * that duplicates `@payloadcms/ui` React context →
 * `Cannot destructure property 'config' of useConfig() as it is undefined`.
 *
 * List search still uses `diacriticAdminSearchPlugin` (searchFold). Typeahead
 * folding needs a non-alias approach (pnpm patch / local Select override).
 */
// Relative file import bypasses package "exports" + avoids alias loop on payload/shared.
import * as Shared from '../../node_modules/payload/dist/exports/shared.js'
import { foldWordBoundariesRegex } from '../lib/fold-word-boundaries'

/** Re-export payload/shared with diacritic-insensitive wordBoundariesRegex. */
export const wordBoundariesRegex = foldWordBoundariesRegex

export const {
  BASE_36_DIGITS,
  PREFERENCE_KEYS,
  addSessionToUser,
  appendUploadSelectFields,
  applyLocaleFiltering,
  array,
  blocks,
  buildFolderWhereConstraints,
  checkbox,
  code,
  collectionDefaults,
  combineWhereConstraints,
  confirmPassword,
  date,
  deepCopyObject,
  deepCopyObjectComplex,
  deepCopyObjectSimple,
  deepCopyObjectSimpleWithoutReactComponents,
  deepMerge,
  deepMergeSimple,
  deepMergeWithCombinedArrays,
  deepMergeWithReactComponents,
  deepMergeWithSourceArrays,
  defaultTimezones,
  email,
  extractID,
  fieldAffectsData,
  fieldHasMaxDepth,
  fieldHasSubFields,
  fieldIsArrayType,
  fieldIsBlockType,
  fieldIsGroupType,
  fieldIsHiddenOrDisabled,
  fieldIsID,
  fieldIsLocalized,
  fieldIsPresentationalOnly,
  fieldIsSidebar,
  fieldIsVirtual,
  fieldShouldBeLocalized,
  fieldSupportsMany,
  flattenAllFields,
  flattenTopLevelFields,
  formatAdminURL,
  formatFilesize,
  formatFolderOrDocumentItem,
  formatLabels,
  generateCookie,
  generateExpiredPayloadCookie,
  generateKeyBetween,
  generateNKeysBetween,
  generatePayloadCookie,
  getAutosaveInterval,
  getBestFitFromSizes,
  getCookieExpiration,
  getDataByPath,
  getFieldPaths,
  getFieldPermissions,
  getFromImportMap,
  getLoginOptions,
  getObjectDotNotation,
  getSafeRedirect,
  getSelectMode,
  getSiblingData,
  getUniqueListBy,
  getVersionsMax,
  groupHasName,
  hasAutosaveEnabled,
  hasDraftValidationEnabled,
  hasDraftsEnabled,
  hasLocalizeStatusEnabled,
  hasScheduledPublishEnabled,
  hoistQueryParamsToAnd,
  isImage,
  isNextBuild,
  isNumber,
  isPlainObject,
  isReactClientComponent,
  isReactComponentOrFunction,
  isReactServerComponentOrFunction,
  json,
  mergeListSearchAndWhere,
  number,
  optionIsObject,
  optionIsValue,
  optionsAreObjects,
  parseCookies,
  parsePayloadComponent,
  password,
  point,
  radio,
  reduceFieldsToValues,
  relationship,
  removeExpiredSessions,
  richText,
  sanitizeFilename,
  sanitizeUrl,
  sanitizeUserDataForEmail,
  select,
  serverProps,
  setsAreEqual,
  slugify,
  tabHasName,
  text,
  textarea,
  toKebabCase,
  toWords,
  transformColumnsToPreferences,
  transformColumnsToSearchParams,
  transformWhereQuery,
  unflatten,
  upload,
  username,
  validOperatorSet,
  validOperators,
  validateBlocksFilterOptions,
  validateMimeType,
  validateWhereQuery,
  validations,
  valueIsValueWithRelation,
  versionDefaults,
  wait,
} = Shared
