/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    stranky: Stranky;
    aktuality: Aktuality;
    kalendar: Kalendar;
    projekty: Projekty;
    workshopy: Workshopy;
    publikace: Publikace;
    lide: Lide;
    tags: Tag;
    'workshop-audiences': WorkshopAudience;
    'publication-types': PublicationType;
    sites: Site;
    users: User;
    media: Media;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    workshopy: {
      scheduledWorkshops: 'kalendar';
    };
  };
  collectionsSelect: {
    stranky: StrankySelect<false> | StrankySelect<true>;
    aktuality: AktualitySelect<false> | AktualitySelect<true>;
    kalendar: KalendarSelect<false> | KalendarSelect<true>;
    projekty: ProjektySelect<false> | ProjektySelect<true>;
    workshopy: WorkshopySelect<false> | WorkshopySelect<true>;
    publikace: PublikaceSelect<false> | PublikaceSelect<true>;
    lide: LideSelect<false> | LideSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'workshop-audiences': WorkshopAudiencesSelect<false> | WorkshopAudiencesSelect<true>;
    'publication-types': PublicationTypesSelect<false> | PublicationTypesSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stranky".
 */
export interface Stranky {
  id: number;
  coverImage?: (number | null) | Media;
  headerColor?: string | null;
  title: string;
  /**
   * Krátký text v přehledech a na detailu.
   */
  excerpt?: string | null;
  /**
   * Univerzální bloky
   */
  content?:
    | (
        | {
            segments?:
              | {
                  text: string;
                  underline?: string | null;
                  id?: string | null;
                }[]
              | null;
            subheadline?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            selection?: ('auto' | 'manual') | null;
            /**
             * Min. 3, max. 6.
             */
            limit?: number | null;
            /**
             * Min. 3, max. 6 událostí.
             */
            items?: (number | Kalendar)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'events';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            pillars?:
              | {
                  color: string;
                  title: string;
                  body: string;
                  buttonLabel?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pillars';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            selection?: ('auto' | 'manual') | null;
            /**
             * Min. 4, max. 8.
             */
            limit?: number | null;
            /**
             * Min. 4, max. 8 aktualit.
             */
            items?: (number | Aktuality)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Vyberte projekty a seřaďte je přetažením.
             */
            items: (number | Projekty)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            /**
             * Max. 3 sloupce — na frontendu vždy přes celou šířku kontejneru.
             */
            columns?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            headerColor?: string | null;
            /**
             * Pokud je nastaven, překryje barevné pozadí.
             */
            coverImage?: (number | null) | Media;
            lead?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageIntro';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Pouze obrázky — video patří do samostatného bloku.
             */
            images: (number | Media)[];
            /**
             * Počet sloupců mřížky na desktopu (1–3).
             */
            columns?: ('1' | '2' | '3') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title: string;
            /**
             * Jména lektorů u workshopu (odděleně od kontaktu Lidé).
             */
            people?:
              | {
                  name: string;
                  role?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'speakers';
          }
        | {
            title: string;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
      )[]
    | null;
  /**
   * Univerzální bloky domovské stránky
   */
  homepageContent?:
    | (
        | {
            segments?:
              | {
                  text: string;
                  underline?: string | null;
                  id?: string | null;
                }[]
              | null;
            subheadline?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            selection?: ('auto' | 'manual') | null;
            /**
             * Min. 3, max. 6.
             */
            limit?: number | null;
            /**
             * Min. 3, max. 6 událostí.
             */
            items?: (number | Kalendar)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'events';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            pillars?:
              | {
                  color: string;
                  title: string;
                  body: string;
                  buttonLabel?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pillars';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            selection?: ('auto' | 'manual') | null;
            /**
             * Min. 4, max. 8.
             */
            limit?: number | null;
            /**
             * Min. 4, max. 8 aktualit.
             */
            items?: (number | Aktuality)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Vyberte projekty a seřaďte je přetažením.
             */
            items: (number | Projekty)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            /**
             * Max. 3 sloupce — na frontendu vždy přes celou šířku kontejneru.
             */
            columns?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            headerColor?: string | null;
            /**
             * Pokud je nastaven, překryje barevné pozadí.
             */
            coverImage?: (number | null) | Media;
            lead?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageIntro';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Pouze obrázky — video patří do samostatného bloku.
             */
            images: (number | Media)[];
            /**
             * Počet sloupců mřížky na desktopu (1–3).
             */
            columns?: ('1' | '2' | '3') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title: string;
            /**
             * Jména lektorů u workshopu (odděleně od kontaktu Lidé).
             */
            people?:
              | {
                  name: string;
                  role?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'speakers';
          }
        | {
            title: string;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
      )[]
    | null;
  /**
   * Na každém webu může být jen jedna domovská stránka.
   */
  isHomepage?: boolean | null;
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  /**
   * Volitelný přepis výchozího SEO titulku stránky.
   */
  metaTitle?: string | null;
  /**
   * Volitelný přepis meta popisu pro vyhledávače a sdílení.
   */
  description?: string | null;
  /**
   * Volitelný přepis výchozího sdílecího obrázku z nastavení webu.
   */
  sharingImage?: (number | null) | Media;
  /**
   * Volitelná kanonická URL adresa.
   */
  canonicalURL?: string | null;
  /**
   * Zakáže indexaci stránky ve vyhledávačích.
   */
  noindex?: boolean | null;
  /**
   * Web, na kterém se stránka zobrazí.
   */
  site: number | Site;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Popis obrázku pro přístupnost a SEO.
   */
  alt: string;
  /**
   * Volitelný popisek u obrázku v obsahu.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kalendar".
 */
export interface Kalendar {
  id: number;
  /**
   * Plakát nebo ilustrace události.
   */
  coverImage?: (number | null) | Media;
  startDate: string;
  endDate?: string | null;
  tags?: (number | Tag)[] | null;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  location?: {
    name?: string | null;
    city?: string | null;
    address?: string | null;
    /**
     * Název venue (např. Hlavní nádraží Brno).
     */
    venue?: string | null;
    /**
     * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
     */
    mapsLink?: string | null;
  };
  /**
   * Volitelné. Zobrazit event když uživatel klikne na tlačítko "Aktuální termíny" na stránce workshopu.
   */
  workshop?: (number | null) | Workshopy;
  /**
   * Hlavní výzvy (Přihlásit se, ...).
   */
  ctas?:
    | {
        title: string;
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  /**
   * Volitelný přepis výchozího SEO titulku stránky.
   */
  metaTitle?: string | null;
  /**
   * Volitelný přepis meta popisu pro vyhledávače a sdílení.
   */
  description?: string | null;
  /**
   * Volitelný přepis výchozího sdílecího obrázku z nastavení webu.
   */
  sharingImage?: (number | null) | Media;
  /**
   * Volitelná kanonická URL adresa.
   */
  canonicalURL?: string | null;
  /**
   * Zakáže indexaci stránky ve vyhledávačích.
   */
  noindex?: boolean | null;
  /**
   * Kdo vytvořil tento obsah — nezobrazuje se na webu.
   */
  author?: (number | null) | User;
  /**
   * Kde se událost zobrazí.
   */
  site: number | Site;
  /**
   * Zobrazí obsah kromě aktuálního webu i na hlavním webu NaZemi.
   */
  showOnMainSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshopy".
 */
export interface Workshopy {
  id: number;
  coverImage?: (number | null) | Media;
  /**
   * Volný text (např. 6 hodin, 2 dny).
   */
  duration?: string | null;
  /**
   * Např. 12–24 účastníků.
   */
  groupSize?: string | null;
  /**
   * Volný text (např. 12 000 – 18 000 Kč).
   */
  price?: string | null;
  topics?: (number | Tag)[] | null;
  audiences?: (number | WorkshopAudience)[] | null;
  title: string;
  /**
   * Krátký text v přehledech a na detailu.
   */
  excerpt?: string | null;
  takeaways?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Univerzální bloky včetně Textového, lektorů a referencí.
   */
  blocks?:
    | (
        | {
            segments?:
              | {
                  text: string;
                  underline?: string | null;
                  id?: string | null;
                }[]
              | null;
            subheadline?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            selection?: ('auto' | 'manual') | null;
            /**
             * Min. 3, max. 6.
             */
            limit?: number | null;
            /**
             * Min. 3, max. 6 událostí.
             */
            items?: (number | Kalendar)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'events';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            pillars?:
              | {
                  color: string;
                  title: string;
                  body: string;
                  buttonLabel?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pillars';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            selection?: ('auto' | 'manual') | null;
            /**
             * Min. 4, max. 8.
             */
            limit?: number | null;
            /**
             * Min. 4, max. 8 aktualit.
             */
            items?: (number | Aktuality)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Vyberte projekty a seřaďte je přetažením.
             */
            items: (number | Projekty)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            title?: string | null;
            /**
             * Max. 2 tlačítka
             */
            actions?:
              | {
                  label: string;
                  /**
                   * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
                   */
                  href: string;
                  variant?: ('filled' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            /**
             * Max. 3 sloupce — na frontendu vždy přes celou šířku kontejneru.
             */
            columns?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            headerColor?: string | null;
            /**
             * Pokud je nastaven, překryje barevné pozadí.
             */
            coverImage?: (number | null) | Media;
            lead?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageIntro';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Pouze obrázky — video patří do samostatného bloku.
             */
            images: (number | Media)[];
            /**
             * Počet sloupců mřížky na desktopu (1–3).
             */
            columns?: ('1' | '2' | '3') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            title: string;
            /**
             * Jména lektorů u workshopu (odděleně od kontaktu Lidé).
             */
            people?:
              | {
                  name: string;
                  role?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'speakers';
          }
        | {
            title: string;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
      )[]
    | null;
  /**
   * Objednávka / externí odkaz v hlavičce.
   */
  ctas?:
    | {
        title: string;
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Propojené termíny z Kalendáře (vznikají u události polem Workshop).
   */
  scheduledWorkshops?: {
    docs?: (number | Kalendar)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  /**
   * Volitelný přepis výchozího SEO titulku stránky.
   */
  metaTitle?: string | null;
  /**
   * Volitelný přepis meta popisu pro vyhledávače a sdílení.
   */
  description?: string | null;
  /**
   * Volitelný přepis výchozího sdílecího obrázku z nastavení webu.
   */
  sharingImage?: (number | null) | Media;
  /**
   * Volitelná kanonická URL adresa.
   */
  canonicalURL?: string | null;
  /**
   * Zakáže indexaci stránky ve vyhledávačích.
   */
  noindex?: boolean | null;
  /**
   * Kdo vytvořil tento obsah — nezobrazuje se na webu.
   */
  author?: (number | null) | User;
  /**
   * Na kterém webu se workshop nabízí.
   */
  site: number | Site;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-audiences".
 */
export interface WorkshopAudience {
  id: number;
  title: string;
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aktuality".
 */
export interface Aktuality {
  id: number;
  /**
   * Náhled v přehledech a u sdílení.
   */
  coverImage?: (number | null) | Media;
  publishedAt: string;
  /**
   * Velký = obrázek na celou šířku; malý = obrázek tak, aby se vešel do hlavičky celý.
   */
  layout?: ('big' | 'small') | null;
  /**
   * Volitelné kategorizace v přehledech.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Vyplníte-li, karta článku bude odkazovat na externí odkaz(↗) místo na článek na našem webu. Relativní (/…) nebo https://…
   */
  externalUrl?: string | null;
  title: string;
  /**
   * Veřejný podpis u článku. Předvyplní se z interního editora; můžete změnit.
   */
  authorName?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  /**
   * Volitelný přepis výchozího SEO titulku stránky.
   */
  metaTitle?: string | null;
  /**
   * Volitelný přepis meta popisu pro vyhledávače a sdílení.
   */
  description?: string | null;
  /**
   * Volitelný přepis výchozího sdílecího obrázku z nastavení webu.
   */
  sharingImage?: (number | null) | Media;
  /**
   * Volitelná kanonická URL adresa.
   */
  canonicalURL?: string | null;
  /**
   * Zakáže indexaci stránky ve vyhledávačích.
   */
  noindex?: boolean | null;
  /**
   * Kdo vytvořil tento obsah — nezobrazuje se na webu.
   */
  author?: (number | null) | User;
  /**
   * Kde se aktualita zobrazí.
   */
  site: number | Site;
  /**
   * Zobrazí obsah kromě aktuálního webu i na hlavním webu NaZemi.
   */
  showOnMainSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Administrátor spravuje weby a uživatele; editor spravuje obsah.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  slug: string;
  siteType: 'main' | 'subsite';
  /**
   * Produkční host; lokálně stačí ?site=slug.
   */
  subdomain?: string | null;
  logo?: (number | null) | Media;
  /**
   * Ilustrace / obrázek za hero blokem na domovské stránce. Bez výběru se použije výchozí vlna.
   */
  homepageBackground?: (number | null) | Media;
  /**
   * Texty, rámečky a navigace — na hlavním webu barva „ground“ (earth). CSS hex, např. #7C3AED.
   */
  primaryColor?: string | null;
  /**
   * Pozadí stránek a světlé plochy — na hlavním webu barva „sky“.
   */
  primaryBackgroundColor?: string | null;
  /**
   * Call to Action tlačítka (filled green / přihlášení) — na hlavním webu zelená.
   */
  accentColor?: string | null;
  additionalColors?:
    | {
        label?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hlavní navigace. Interní odkaz = kolekce → položka; externí = URL. Podpoložky jen u hlavní úrovně.
   */
  mainMenu?:
    | {
        /**
         * Volitelné u interního odkazu — prázdné → název vybrané položky.
         */
        label?: string | null;
        linkType: 'internal' | 'external';
        /**
         * Vyberte kolekci a záznam.
         */
        reference?:
          | ({
              relationTo: 'stranky';
              value: number | Stranky;
            } | null)
          | ({
              relationTo: 'aktuality';
              value: number | Aktuality;
            } | null)
          | ({
              relationTo: 'kalendar';
              value: number | Kalendar;
            } | null)
          | ({
              relationTo: 'workshopy';
              value: number | Workshopy;
            } | null)
          | ({
              relationTo: 'publikace';
              value: number | Publikace;
            } | null)
          | ({
              relationTo: 'projekty';
              value: number | Projekty;
            } | null);
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        href?: string | null;
        children?:
          | {
              /**
               * Volitelné u interního odkazu — prázdné → název vybrané položky.
               */
              label?: string | null;
              linkType: 'internal' | 'external';
              /**
               * Vyberte kolekci a záznam.
               */
              reference?:
                | ({
                    relationTo: 'stranky';
                    value: number | Stranky;
                  } | null)
                | ({
                    relationTo: 'aktuality';
                    value: number | Aktuality;
                  } | null)
                | ({
                    relationTo: 'kalendar';
                    value: number | Kalendar;
                  } | null)
                | ({
                    relationTo: 'workshopy';
                    value: number | Workshopy;
                  } | null)
                | ({
                    relationTo: 'publikace';
                    value: number | Publikace;
                  } | null)
                | ({
                    relationTo: 'projekty';
                    value: number | Projekty;
                  } | null);
              /**
               * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
               */
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Vedlejší odkazy (např. externí weby). Stejný model jako hlavní menu, bez podpoložek.
   */
  secondaryMenu?:
    | {
        /**
         * Volitelné u interního odkazu — prázdné → název vybrané položky.
         */
        label?: string | null;
        linkType: 'internal' | 'external';
        /**
         * Vyberte kolekci a záznam.
         */
        reference?:
          | ({
              relationTo: 'stranky';
              value: number | Stranky;
            } | null)
          | ({
              relationTo: 'aktuality';
              value: number | Aktuality;
            } | null)
          | ({
              relationTo: 'kalendar';
              value: number | Kalendar;
            } | null)
          | ({
              relationTo: 'workshopy';
              value: number | Workshopy;
            } | null)
          | ({
              relationTo: 'publikace';
              value: number | Publikace;
            } | null)
          | ({
              relationTo: 'projekty';
              value: number | Projekty;
            } | null);
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Odkazy v patičce webu.
   */
  socialLinks?:
    | {
        network: string;
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  contactDetails?:
    | {
        title: string;
        email?: string | null;
        phone?: string | null;
        addressLines?:
          | {
              line: string;
              id?: string | null;
            }[]
          | null;
        note?: string | null;
        links?:
          | {
              label: string;
              /**
               * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        extras?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Zpětná kompatibilita — preferujte e-mail, telefon a řádky adresy.
         */
        legacyPlainText?: string | null;
        id?: string | null;
      }[]
    | null;
  fullAddress?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  additionalContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  donateCta?: {
    title?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
    /**
     * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
     */
    href?: string | null;
  };
  newsletters?:
    | {
        title: string;
        description?: string | null;
        subscribeLabel?: string | null;
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        subscribeUrl: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Výchozí titulek prohlížeče / sdílení.
   */
  metaTitle?: string | null;
  /**
   * Výchozí meta popis webu.
   */
  description?: string | null;
  /**
   * Výchozí obrázek pro sociální sítě.
   */
  sharingImage?: (number | null) | Media;
  canonicalURL?: string | null;
  /**
   * Zakáže indexaci celého webu ve vyhledávačích.
   */
  noindex?: boolean | null;
  /**
   * Vypne sekci na frontendu (menu + stránky výpisu).
   */
  enabledCollections?: {
    /**
     * Přehled a detaily aktualit.
     */
    aktuality?: boolean | null;
    /**
     * Přehled a detaily událostí.
     */
    kalendar?: boolean | null;
    /**
     * Projekty jsou k dispozici pouze pro hlavní web.
     */
    projekty?: boolean | null;
    workshopy?: boolean | null;
    publikace?: boolean | null;
    /**
     * Sekce lidí na stránce Kontakt.
     */
    lide?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikace".
 */
export interface Publikace {
  id: number;
  coverImage: number | Media;
  types?: (number | PublicationType)[] | null;
  topics?: (number | Tag)[] | null;
  title: string;
  /**
   * Veřejný podpis u článku. Předvyplní se z interního editora; můžete změnit.
   */
  authorName?: string | null;
  /**
   * Krátký text v přehledech a na detailu.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Odkazy u publikace (kde koupit,...)
   */
  ctas?:
    | {
        title: string;
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  /**
   * Volitelný přepis výchozího SEO titulku stránky.
   */
  metaTitle?: string | null;
  /**
   * Volitelný přepis meta popisu pro vyhledávače a sdílení.
   */
  description?: string | null;
  /**
   * Volitelný přepis výchozího sdílecího obrázku z nastavení webu.
   */
  sharingImage?: (number | null) | Media;
  /**
   * Volitelná kanonická URL adresa.
   */
  canonicalURL?: string | null;
  /**
   * Zakáže indexaci stránky ve vyhledávačích.
   */
  noindex?: boolean | null;
  /**
   * Kdo vytvořil tento obsah — nezobrazuje se na webu.
   */
  author?: (number | null) | User;
  /**
   * Kde se publikace zobrazí.
   */
  site: number | Site;
  /**
   * Zobrazí obsah kromě aktuálního webu i na hlavním webu NaZemi.
   */
  showOnMainSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-types".
 */
export interface PublicationType {
  id: number;
  title: string;
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekty".
 */
export interface Projekty {
  id: number;
  /**
   * Značka projektu v přehledech.
   */
  logo?: (number | null) | Media;
  /**
   * Barva pruhu v přehledu a detailu (Doplňkové barvy webu).
   */
  projectColor?: string | null;
  /**
   * Tailwind třídy velikosti loga, např. h-[95px] w-[150px].
   */
  logoClass?: string | null;
  title: string;
  /**
   * Krátký text v přehledech a na detailu.
   */
  excerpt?: string | null;
  /**
   * Univerzální bloky (včetně Textového a galerie).
   */
  content: (
    | {
        segments?:
          | {
              text: string;
              underline?: string | null;
              id?: string | null;
            }[]
          | null;
        subheadline?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        title?: string | null;
        /**
         * Max. 2 tlačítka
         */
        actions?:
          | {
              label: string;
              /**
               * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
               */
              href: string;
              variant?: ('filled' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        selection?: ('auto' | 'manual') | null;
        /**
         * Min. 3, max. 6.
         */
        limit?: number | null;
        /**
         * Min. 3, max. 6 událostí.
         */
        items?: (number | Kalendar)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'events';
      }
    | {
        title?: string | null;
        /**
         * Max. 2 tlačítka
         */
        actions?:
          | {
              label: string;
              /**
               * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
               */
              href: string;
              variant?: ('filled' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        pillars?:
          | {
              color: string;
              title: string;
              body: string;
              buttonLabel?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pillars';
      }
    | {
        title?: string | null;
        /**
         * Max. 2 tlačítka
         */
        actions?:
          | {
              label: string;
              /**
               * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
               */
              href: string;
              variant?: ('filled' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        selection?: ('auto' | 'manual') | null;
        /**
         * Min. 4, max. 8.
         */
        limit?: number | null;
        /**
         * Min. 4, max. 8 aktualit.
         */
        items?: (number | Aktuality)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'news';
      }
    | {
        title?: string | null;
        /**
         * Max. 2 tlačítka
         */
        actions?:
          | {
              label: string;
              /**
               * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
               */
              href: string;
              variant?: ('filled' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Vyberte projekty a seřaďte je přetažením.
         */
        items: (number | Projekty)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'projects';
      }
    | {
        title?: string | null;
        /**
         * Max. 2 tlačítka
         */
        actions?:
          | {
              label: string;
              /**
               * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
               */
              href: string;
              variant?: ('filled' | 'outline') | null;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        /**
         * Max. 3 sloupce — na frontendu vždy přes celou šířku kontejneru.
         */
        columns?:
          | {
              title: string;
              body: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'about';
      }
    | {
        headerColor?: string | null;
        /**
         * Pokud je nastaven, překryje barevné pozadí.
         */
        coverImage?: (number | null) | Media;
        lead?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pageIntro';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        /**
         * Pouze obrázky — video patří do samostatného bloku.
         */
        images: (number | Media)[];
        /**
         * Počet sloupců mřížky na desktopu (1–3).
         */
        columns?: ('1' | '2' | '3') | null;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        title: string;
        /**
         * Jména lektorů u workshopu (odděleně od kontaktu Lidé).
         */
        people?:
          | {
              name: string;
              role?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'speakers';
      }
    | {
        title: string;
        items?:
          | {
              quote: string;
              author: string;
              role?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
  )[];
  /**
   * Odkazy u projektu.
   */
  ctas?:
    | {
        title: string;
        /**
         * Relativní cesta (/aktuality) nebo absolutní URL (https://…).
         */
        url: string;
        variant?: ('filled' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Vygeneruje se z názvu při prvním uložení.
   */
  slug: string;
  /**
   * Volitelný přepis výchozího SEO titulku stránky.
   */
  metaTitle?: string | null;
  /**
   * Volitelný přepis meta popisu pro vyhledávače a sdílení.
   */
  description?: string | null;
  /**
   * Volitelný přepis výchozího sdílecího obrázku z nastavení webu.
   */
  sharingImage?: (number | null) | Media;
  /**
   * Volitelná kanonická URL adresa.
   */
  canonicalURL?: string | null;
  /**
   * Zakáže indexaci stránky ve vyhledávačích.
   */
  noindex?: boolean | null;
  /**
   * Projekty jsou vázané na hlavní web.
   */
  site: number | Site;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lide".
 */
export interface Lide {
  id: number;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  name: string;
  /**
   * Vygeneruje se ze jména při prvním uložení.
   */
  slug?: string | null;
  role?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Web, na kterém se osoba zobrazí v kontaktech.
   */
  site: number | Site;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'stranky';
        value: number | Stranky;
      }
    | {
        relationTo: 'aktuality';
        value: number | Aktuality;
      }
    | {
        relationTo: 'kalendar';
        value: number | Kalendar;
      }
    | {
        relationTo: 'projekty';
        value: number | Projekty;
      }
    | {
        relationTo: 'workshopy';
        value: number | Workshopy;
      }
    | {
        relationTo: 'publikace';
        value: number | Publikace;
      };
  /**
   * Indexovaný úryvek pro fulltext a snippety.
   */
  excerpt?: string | null;
  /**
   * Normalizovaný text (bez diakritiky + české stemy) pro fulltextové hledání.
   */
  searchText?: string | null;
  collectionSlug?: string | null;
  docSlug?: string | null;
  site?: (number | null) | Site;
  authorName?: string | null;
  publishedAt?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  eventIsPast?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'stranky';
        value: number | Stranky;
      } | null)
    | ({
        relationTo: 'aktuality';
        value: number | Aktuality;
      } | null)
    | ({
        relationTo: 'kalendar';
        value: number | Kalendar;
      } | null)
    | ({
        relationTo: 'projekty';
        value: number | Projekty;
      } | null)
    | ({
        relationTo: 'workshopy';
        value: number | Workshopy;
      } | null)
    | ({
        relationTo: 'publikace';
        value: number | Publikace;
      } | null)
    | ({
        relationTo: 'lide';
        value: number | Lide;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'workshop-audiences';
        value: number | WorkshopAudience;
      } | null)
    | ({
        relationTo: 'publication-types';
        value: number | PublicationType;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stranky_select".
 */
export interface StrankySelect<T extends boolean = true> {
  coverImage?: T;
  headerColor?: T;
  title?: T;
  excerpt?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              segments?:
                | T
                | {
                    text?: T;
                    underline?: T;
                    id?: T;
                  };
              subheadline?: T;
              id?: T;
              blockName?: T;
            };
        events?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              pillars?:
                | T
                | {
                    color?: T;
                    title?: T;
                    body?: T;
                    buttonLabel?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              items?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              image?: T;
              columns?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageIntro?:
          | T
          | {
              headerColor?: T;
              coverImage?: T;
              lead?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              columns?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        speakers?:
          | T
          | {
              title?: T;
              people?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  homepageContent?:
    | T
    | {
        hero?:
          | T
          | {
              segments?:
                | T
                | {
                    text?: T;
                    underline?: T;
                    id?: T;
                  };
              subheadline?: T;
              id?: T;
              blockName?: T;
            };
        events?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              pillars?:
                | T
                | {
                    color?: T;
                    title?: T;
                    body?: T;
                    buttonLabel?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              items?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              image?: T;
              columns?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageIntro?:
          | T
          | {
              headerColor?: T;
              coverImage?: T;
              lead?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              columns?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        speakers?:
          | T
          | {
              title?: T;
              people?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  isHomepage?: T;
  slug?: T;
  metaTitle?: T;
  description?: T;
  sharingImage?: T;
  canonicalURL?: T;
  noindex?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aktuality_select".
 */
export interface AktualitySelect<T extends boolean = true> {
  coverImage?: T;
  publishedAt?: T;
  layout?: T;
  tags?: T;
  externalUrl?: T;
  title?: T;
  authorName?: T;
  content?: T;
  slug?: T;
  metaTitle?: T;
  description?: T;
  sharingImage?: T;
  canonicalURL?: T;
  noindex?: T;
  author?: T;
  site?: T;
  showOnMainSite?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kalendar_select".
 */
export interface KalendarSelect<T extends boolean = true> {
  coverImage?: T;
  startDate?: T;
  endDate?: T;
  tags?: T;
  title?: T;
  content?: T;
  location?:
    | T
    | {
        name?: T;
        city?: T;
        address?: T;
        venue?: T;
        mapsLink?: T;
      };
  workshop?: T;
  ctas?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  metaTitle?: T;
  description?: T;
  sharingImage?: T;
  canonicalURL?: T;
  noindex?: T;
  author?: T;
  site?: T;
  showOnMainSite?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projekty_select".
 */
export interface ProjektySelect<T extends boolean = true> {
  logo?: T;
  projectColor?: T;
  logoClass?: T;
  title?: T;
  excerpt?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              segments?:
                | T
                | {
                    text?: T;
                    underline?: T;
                    id?: T;
                  };
              subheadline?: T;
              id?: T;
              blockName?: T;
            };
        events?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              pillars?:
                | T
                | {
                    color?: T;
                    title?: T;
                    body?: T;
                    buttonLabel?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              items?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              image?: T;
              columns?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageIntro?:
          | T
          | {
              headerColor?: T;
              coverImage?: T;
              lead?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              columns?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        speakers?:
          | T
          | {
              title?: T;
              people?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  ctas?:
    | T
    | {
        title?: T;
        url?: T;
        variant?: T;
        id?: T;
      };
  slug?: T;
  metaTitle?: T;
  description?: T;
  sharingImage?: T;
  canonicalURL?: T;
  noindex?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshopy_select".
 */
export interface WorkshopySelect<T extends boolean = true> {
  coverImage?: T;
  duration?: T;
  groupSize?: T;
  price?: T;
  topics?: T;
  audiences?: T;
  title?: T;
  excerpt?: T;
  takeaways?:
    | T
    | {
        item?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              segments?:
                | T
                | {
                    text?: T;
                    underline?: T;
                    id?: T;
                  };
              subheadline?: T;
              id?: T;
              blockName?: T;
            };
        events?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              pillars?:
                | T
                | {
                    color?: T;
                    title?: T;
                    body?: T;
                    buttonLabel?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              selection?: T;
              limit?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              items?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              image?: T;
              columns?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageIntro?:
          | T
          | {
              headerColor?: T;
              coverImage?: T;
              lead?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              columns?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        speakers?:
          | T
          | {
              title?: T;
              people?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  ctas?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  scheduledWorkshops?: T;
  slug?: T;
  metaTitle?: T;
  description?: T;
  sharingImage?: T;
  canonicalURL?: T;
  noindex?: T;
  author?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikace_select".
 */
export interface PublikaceSelect<T extends boolean = true> {
  coverImage?: T;
  types?: T;
  topics?: T;
  title?: T;
  authorName?: T;
  excerpt?: T;
  content?: T;
  ctas?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  metaTitle?: T;
  description?: T;
  sharingImage?: T;
  canonicalURL?: T;
  noindex?: T;
  author?: T;
  site?: T;
  showOnMainSite?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lide_select".
 */
export interface LideSelect<T extends boolean = true> {
  image?: T;
  sortOrder?: T;
  name?: T;
  slug?: T;
  role?: T;
  phone?: T;
  email?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-audiences_select".
 */
export interface WorkshopAudiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-types_select".
 */
export interface PublicationTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  siteType?: T;
  subdomain?: T;
  logo?: T;
  homepageBackground?: T;
  primaryColor?: T;
  primaryBackgroundColor?: T;
  accentColor?: T;
  additionalColors?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  mainMenu?:
    | T
    | {
        label?: T;
        linkType?: T;
        reference?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              reference?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  secondaryMenu?:
    | T
    | {
        label?: T;
        linkType?: T;
        reference?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  contactDetails?:
    | T
    | {
        title?: T;
        email?: T;
        phone?: T;
        addressLines?:
          | T
          | {
              line?: T;
              id?: T;
            };
        note?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        extras?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        legacyPlainText?: T;
        id?: T;
      };
  fullAddress?: T;
  additionalContent?: T;
  donateCta?:
    | T
    | {
        title?: T;
        body?: T;
        buttonLabel?: T;
        href?: T;
      };
  newsletters?:
    | T
    | {
        title?: T;
        description?: T;
        subscribeLabel?: T;
        subscribeUrl?: T;
        id?: T;
      };
  metaTitle?: T;
  description?: T;
  sharingImage?: T;
  canonicalURL?: T;
  noindex?: T;
  enabledCollections?:
    | T
    | {
        aktuality?: T;
        kalendar?: T;
        projekty?: T;
        workshopy?: T;
        publikace?: T;
        lide?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  excerpt?: T;
  searchText?: T;
  collectionSlug?: T;
  docSlug?: T;
  site?: T;
  authorName?: T;
  publishedAt?: T;
  startDate?: T;
  endDate?: T;
  eventIsPast?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}